apiVersion: v1
kind: Service
metadata:
  name: {{ include "rosette-server.fullname" . }}-lb
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rosette-server.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  sessionAffinity: {{ .Values.loadbalancer.sessionAffinity }}
  ports:
    - port: {{ .Values.loadbalancer.port }}
      targetPort: {{ .Values.rsimage.portName }}
      protocol: TCP
      name: http
  